typography_spectrum: 0.04519000509753823
color:
  brandStrength: 0.8464813521131873
  lightness: 0.07068285276181996
  saturation: 0.5700502719264477
  rhythmicContrast: 0.8017406587023288
  brandColors:
    - '#B9121B'
    - '#4C1B1B'
    - '#F6E497'
    - '#FCFAE1'
    - '#BD8D46'
layout_spectrum: 0.8291248988825828
name: Skateboards
style: the-composer
navigation:
  - name: Boosted
    url: 'https://boostedboards.com/'
    type: external
  - name: Hipster as Fuck
    id: 4842987e-86e4-4817-871d-88d3662842ec
    type: content
  - name: Test
    url: 'http://g.recordit.co/rqOnJYqI4H.gif'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4f88f9a2-92e1-429d-8c53-39bac8337455.png
title: Concrete Waves
coverPrefs:
  filter: false
description: Skateboarding is Not a Crime
