typography_spectrum: 0.5344562663231045
color:
  brandStrength: 0.2995454298797995
  lightness: 0.9784989259205759
  saturation: 0.1688914366532117
  rhythmicContrast: 0.25271741580218077
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
layout_spectrum: 0.6431678966619074
name: Skateboards
style: the-composer
navigation:
  - name: Boosted
    url: 'https://boostedboards.com/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4f88f9a2-92e1-429d-8c53-39bac8337455.png
title: Concrete Waves
coverPrefs:
  filter: false
description: Skateboarding is Not a Crime
